apiVersion: v1
kind: Service
metadata:
  name: spring-test-gcp
  namespace: spring-test
spec:
  type: ClusterIP
  selector:
    app: spring-test-gcp
  ports:
    - port: 7000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-test-gcp
  name: spring-test-gcp
  namespace: spring-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-test-gcp
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-test-gcp
      namespace: spring-test
    spec:
      containers:
      - image: taf122/spring-test-gcp:0.1.0
        name: spring-test-gcp
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/opt/secret/secret.json"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: ggcred
          mountPath: "/opt/secret"
          readOnly: true
      volumes:
      - name: ggcred
        secret:
          secretName: ggsecret
          items:
          - key: api-cred
            path: secret.json
